site_name: 'Agent Shredder Doku'
docs_dir: '../../docs/en'                           # Where to find the English markdown files
site_dir: '../../generated/en'                      # Where to put the English HTML files

theme:
  name: material
  custom_dir: '../../overrides/' 
  logo: assets/images/logo.svg
  favicon: assets/images/logo.png
  language: en

  extra:
    homepage: https://agent-shredder.com
  palette:
    scheme: slate
    primary: indigo
    accent: cyan
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - toc.follow
    - toc.integrate

extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Deutsch
      link: /de/
      lang: de

plugins:
  - search:                                         
      lang: en

nav:
  - Display:
    - pages/display/index.md 
    - Graphics: pages/display/graphics.md
    - Status Bars: pages/display/status-bar.md
  - Encryption:
    - pages/encryption/index.md
  - Menu:
    - pages/menu/index.md
  - Shredder:
    - pages/shredder/index.md
