site_name: 'Agent Shredder Doku'
docs_dir: '../../docs/de'                           # Where to find the English markdown files
site_dir: '../../generated/de'                      # Where to put the English HTML files

theme:
  name: material
  custom_dir: '../../overrides/' 
  logo: assets/images/logo.svg
  favicon: assets/images/logo.png
  language: de

  extra:
    homepage: https://agent-shredder.com
  palette:
    scheme: slate
    primary: black
    accent: teal
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
    - toc.integrate
    - search.highlight
    - search.share
    - search.suggest

extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Deutsch
      link: /de/
      lang: de

plugins:
  - search:                                         
      lang: de

nav:
  - Applikation:
    - pages/app/index.md
    - Basis: pages/app/base.md
    - Display: pages/app/display.md
    - Menü: pages/app/menu.md
    - Statusleiste: pages/app/status-bar.md
    - Shredder: pages/app/shredder.md
    - Transfer: pages/app/transfer.md
    - Verschlüsselung: pages/app/encryption.md
    - Container: pages/app/container.md
    - Update: pages/app/update.md
  - Linux:
    - pages/linux/index.md
    - cryptsetup: pages/linux/cryptsetup.md
    - udisks: pages/linux/udisks.md
    - no root: pages/linux/no-root.md
    - rsync: pages/linux/rsync.md
    - blkdiscard: pages/linux/blkdiscard.md
    - exfat: pages/linux/exfat.md
    - gadget mode: pages/linux/gadget.md
    - systemd: pages/linux/systemd.md
    - fstab: pages/linux/fstab.md
    - i2c: pages/linux/i2c.md
    - uboot: pages/linux/uboot.md
    - secure boot: pages/linux/secure-boot.md
  - Hardware:
    - pages/hardware/index.md
    - Montage: pages/hardware/montage.md
    - NanoPi NEO Core: pages/hardware/nanopi.md
    - NanoHat OLED: pages/hardware/nanohat-oled.md
    - Power Hat: pages/hardware/power-hat.md
    - I2C: pages/hardware/i2c.md
    - UART: pages/hardware/uart.md
    - RTC: pages/hardware/rtc.md
    - Fuel Gauge: pages/hardware/fuel-gauge.md
    - 5V Boost: pages/hardware/boost.md
    - Charger: pages/hardware/charger.md
    - Accelerometer: pages/hardware/accelerometer.md
